# Combining Human & Mouse libraries

In [1]:
import numpy as np
import gffutils
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd 
from pegg import prime
import Bio.Seq

/Users/samgould/opt/anaconda3/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(


In [24]:
human = pd.read_csv('Human_tiling_library.csv')
mouse = pd.read_csv('Mouse_tiling_library.csv')

#adding information about whether gRNAs are dupliced as well
u, c= np.unique(human['proto_G+19'], return_counts=True)
dup_human = pd.DataFrame(dict(zip(['protospacer', 'count'],[u,c]))).sort_values(by='count', ascending=False)
dup_human['duplicated_guide'] = [True if i>1 else False for i in dup_human['count']]

for i, val in dup_human.iterrows():

    p = val['protospacer']
    c = val['count']
    d = val['duplicated_guide']

    human.loc[human['proto_G+19']==p, 'duplicated_guide'] = d
    human.loc[human['proto_G+19']==p, 'num_duplicates'] = c
  

In [29]:
#adding information about whether gRNAs are dupliced as well
u, c= np.unique(mouse['proto_G+19'], return_counts=True)
dup_mouse = pd.DataFrame(dict(zip(['protospacer', 'count'],[u,c]))).sort_values(by='count', ascending=False)
dup_mouse['duplicated_guide'] = [True if i>1 else False for i in dup_mouse['count']]

for i, val in dup_mouse.iterrows():

    p = val['protospacer']
    c = val['count']
    d = val['duplicated_guide']

    mouse.loc[mouse['proto_G+19']==p, 'duplicated_guide'] = d
    mouse.loc[mouse['proto_G+19']==p, 'num_duplicates'] = c

In [27]:
np.unique(human['duplicated_guide'], return_counts=True)

(array([False, True], dtype=object), array([31248,   945]))

In [30]:
np.unique(mouse['duplicated_guide'], return_counts=True)

(array([False, True], dtype=object), array([31174,  1114]))

In [31]:
merged = pd.concat((human, mouse)).reset_index(drop=True)

print(len(np.unique(merged['gRNA_id'])))
print(len(np.unique(merged['gRNA_oligo'])))
print(len(np.unique(merged['Hamming_BC'])))
print(len(np.unique(merged['proto_G+19'])))
print(len(np.unique(merged['sensor_wt'])))


64481
64481
64481
58866
62316


In [ ]:
#merged.to_csv('Human_and_Mouse_tiling_libraries.csv', index=False)

In [34]:
np.unique(merged['Pool'], return_counts=True)

(array(['F1-R1', 'F1-R2', 'F1-R3', 'F1-R4', 'F1-R5', 'F1-R6', 'F2-R1',
        'F2-R2', 'F2-R3', 'F2-R4', 'F2-R5', 'F2-R6'], dtype=object),
 array([ 1263,  2046,  5852,  5586,  6934, 10512,  1155,  1984,  6445,
         5135,  7072, 10497]))